Category.create(name: "シャワーヘッド")
Category.create(name: "浴槽")
toilet = Category.create(name: "便器")
toilet_jap = toilet.children.create(name: "和式")
toilet_eu = toilet.children.create(name: "洋式")
toilet_christ = toilet.children.create(name: "ウォシュレット")
toilet_jap.children.create([{name: "ピンク色"}, {name: "ボットン"}, {name: "水洗"}])
toilet_eu.children.create([{name: "イギリス"}, {name: "フランス"}, {name: "ドイツ"}])
toilet_christ.children.create([{name: "ビデ"}, {name: "勢いよく水が出る"}, {name: "人肌"}])
